# Generated by Django 3.0.6 on 2020-08-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Tarvel', 'Tarvel'), ('People', 'People'), ('Sports', 'Sports'), ('Music', 'Music'), ('Tv', 'Tv'), ('Entertainment', 'Entertainment')], max_length=200),
        ),
    ]
