# Generated by Django 3.0.6 on 2020-09-06 05:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_musicpost_post_of_the_day_travelpost_tvpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post_of_the_day',
            name='author',
        ),
        migrations.RemoveField(
            model_name='travelpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tvpost',
            name='author',
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Gas&Oil'), (2, 'Criptocurrency'), (3, 'Currency'), (4, 'Alternationveenergy'), (5, 'Technology')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Gas&Oil'), (2, 'Criptocurrency'), (3, 'Currency'), (4, 'Alternationveenergy'), (5, 'Technology')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post_of_the_day',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Gas&Oil'), (2, 'Criptocurrency'), (3, 'Currency'), (4, 'Alternationveenergy'), (5, 'Technology')], max_length=30, null=True),
        ),
    ]
