# Generated by Django 3.0.6 on 2020-09-14 17:58

from django.db import migrations, models
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEOCHANNEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('Gas&Oil', 'Gas&Oil'), ('Criptocurrency', 'Criptocurrency'), ('Currency', 'Currency'), ('Alternationveenergy', 'Alternationveenergy'), ('Technology', 'Technology')], max_length=200)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
