# Generated by Django 3.0.6 on 2020-09-16 22:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20200916_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Criptocurrency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='GasAndOil',
        ),
        migrations.DeleteModel(
            name='HeaderPost1',
        ),
        migrations.DeleteModel(
            name='HeaderPost2',
        ),
        migrations.DeleteModel(
            name='Post_of_the_day',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
        migrations.AlterField(
            model_name='latestpost',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Gas&Oil'), (2, 'Criptocurrency'), (3, 'Currency'), (5, 'Technology')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='meochannel',
            name='category',
            field=models.CharField(blank=True, choices=[('Gas&Oil', 'Gas&Oil'), ('Criptocurrency', 'Criptocurrency'), ('Currency', 'Currency'), ('Technology', 'Technology')], max_length=200),
        ),
    ]
