# Generated by Django 3.0.6 on 2020-09-17 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20200917_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestpost',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
