# Generated by Django 3.0.6 on 2020-09-18 17:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20200918_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestpost',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Gas&Oil'), (2, 'Economy'), (3, 'Energy'), (5, 'Technology')], max_length=30, null=True),
        ),
    ]
