# Generated by Django 3.0.6 on 2020-09-21 22:09

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20200918_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('post_pic', models.ImageField(blank=True, default='welcome.gif', null=True, upload_to='')),
                ('category', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Gas&Oil'), (2, 'Economy'), (3, 'Energy'), (5, 'Technology')], max_length=30, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
