# Generated by Django 3.0.6 on 2020-09-21 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_headerpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderPost',
        ),
    ]
