# Generated by Django 3.0.6 on 2020-09-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20200924_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestpost',
            name='header',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
